@baseUri=http://localhost:3000/api

### test
POST {{baseUri}}/test

### generate wallpaper
POST {{baseUri}}/gen-wallpaper
Content-Type: application/json

{
    "description":"happy new year 2024"
}

### get wallpapers
GET {{baseUri}}/get-wallpapers